{% set name = "pydoas" %}
{% set version = "2.0.3rc1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2406da53b0edf5c81f59b474cc053efdcc587e2a756f152a575bd96c86f1230e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - pandas

test:
  requires:
    - setuptools
    - pytest
    - python {{ python_min }}
  imports:
    - pydoas
  commands:
    - py.test --pyargs pydoas

about:
  home: https://github.com/jgliss/pydoas.git
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Python toolbox for post analysis of DOAS (Differential Optical Absorbtion Spectroscopy) results
  doc_url: https://pydoas.readthedocs.io
  dev_url: https://github.com/jgliss/pydoas

extra:
  recipe-maintainers:
    - jgliss
