{% set name = "pydoas" %}
{% set version = "2.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3499a48460c5b2cff0aa5b37f21f4faead59e4f071d74e370915d88386414b11

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python 3.11
    - setuptools
    - setuptools_scm
  run:
    - python >=3.11
    - numpy
    - matplotlib-base
    - pandas

test:
  requires:
    - setuptools
    - pytest
    - python 3.11
  source_files:
    - test
  imports:
    - pydoas
  commands:
    - pytest -Wi test

about:
  home: https://github.com/jgliss/pydoas.git
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Python toolbox for post analysis of DOAS (Differential Optical Absorbtion Spectroscopy) results
  doc_url: https://pydoas.readthedocs.io
  dev_url: https://github.com/jgliss/pydoas

extra:
  recipe-maintainers:
    - jgliss
