{% set name = "pydoas" %}
{% set version = "2.1.0rc1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62b63a0b8bbfeef5c85a16b15f724836511ff7270e25fa9fd9ab3ee112a23033

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - pandas

test:
  requires:
    - setuptools
    - pytest
    - python {{ python_min }}
  source_files:
    - test
  imports:
    - pydoas
  commands:
    - pytest -Wi test

about:
  home: https://github.com/jgliss/pydoas.git
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Python toolbox for post analysis of DOAS (Differential Optical Absorbtion Spectroscopy) results
  doc_url: https://pydoas.readthedocs.io
  dev_url: https://github.com/jgliss/pydoas

extra:
  recipe-maintainers:
    - jgliss
