{% set name = "pydoas" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f8cdb69e257ea6d86511135d9aeaebc49808a10c609b4ee7d2c58aca21f5ace

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - matplotlib-base
    - pandas

test:
  requires:
    - setuptools
    - pytest
  imports:
    - pydoas
    - pydoas.test
  commands:
    - py.test --pyargs pydoas

about:
  home: https://github.com/jgliss/pydoas.git
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Python toolbox for post analysis of DOAS (Differential Optical Absorbtion Spectroscopy) results
  doc_url: https://pydoas.readthedocs.io
  dev_url: https://github.com/jgliss/pydoas

extra:
  recipe-maintainers:
    - jgliss
