travis:
  secure:
    BINSTAR_TOKEN: JXhBralTZr/pZK8BQR41AhbrpA9btldpbzyxvKXhE0RcNjwU1ZY4yQQ7I29r7mS+46g51yLMvQEteNKVkQm8vN3iY4w8hrSsSZDyX4ms4A2fD/XUxzcpqKKg0r+J9kIOD2cF0g+/GEcJUTGfngmNc9lRs4FdvGvgxsvU/Soez0VIBvC0ySJ7uJh4QF8ZArMAHyCpOj6iSA3WXnKl3xbqxpqMioxWXeJntXD8V6dKfk+2343XIkNm832kOPCLXLVnt67Us8+gnPtbjorIRSQS0Zov6y0edQkN0C5nSQpCBL/AwO+mM2rd+J+UY5EamNmT26xD9AKqT15bUWaRgfzpT1xjgs5FjJp2ALAMUhwsVkl/yK5AMGhGAytooG0sh174Eg37xRL7c/ve2YirwV0q0JyKygJ8Q7uPUTRI3o2hGmrJxN0Zq9x4I6gjpN85VQv/VcPoIFBt6iF4LbmK0hZypFN1BnFA79XZYU4Cz29q4brVKEiYUdsIbZvWQbm/yhJondOkavxLrtW2qbnUR+AC2wPAXkCABlEg4xVFw4i2UnB6NW7hVxoz6r7toLuCs6/ZHayQHdORSNTm6OeCg4hWmrqgGro+LlH1aQak7TY/2w9wDgTmQEdkAC3J6YTlBLe6f4e18WvXha2hRBqVnjv7bmU/NXhJX55G/bkTiETe258=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
